simulation:
  tick_rate: 20
  ticks_per_snapshot: 1
  width: 15
  height: 15
  num_bushes: 10
  num_organisms: 2      #TODO das in der NEAT-Config, dieser Parameter ist unnötig/unbenutzt
  seed:

server:
  host: "127.0.0.1"
  port: 9001
